name: Chang Liu's Blog 
title: Chang Liu's Blog
markdown: kramdown
timezone : Asia/Shanghai
excerpt_separator: "\n\n\n"
pygments: true
safe: true
auto: true
analytics:
	provider: google
	google: 
		tracking_id: 'UA-57041834-1'

